config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :blog_articals
  resources :events do
    resources :event_comments
  end
  resources :emails
  resources :business_messages
  resources :group_messages
  resources :private_messages
  resources :memberships
  resources :groups
  resources :messages do
    resources :comments
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  
  get 'feed' => 'blog_articles#feed'
  get 'webhook' => 'feeds#webhook'
  post 'webhook' => 'feeds#webhook' 
  get 'subscribe' => 'feeds#subscribe'
  get 'home/index'
  get 'home/profile'
  get 'home/calendar'
  get 'home/leadCandidates'
  get 'home/currentLeads'
  get 'home/userDirectory'
  post 'home/promote'
  post 'home/demote'
  
  
  root 'home#index', as: 'home' 

end

app/models/blog_artical.rb
class BlogArtical < ActiveRecord::Base
end

app/models/business_message.rb
class BusinessMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :event_comments
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :entries, dependent: :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
    after_create :establish_membership
    
    def establish_membership
        Membership.create!(title: self.title, email: (User.find_by(id: self.user_id)).email)
        
    end
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
   private
    before_save {|message| message.group_id = (Group.find_by(title: message.group_name)).id }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :email, uniqueness: { scope: [:title], message: "User is already associated with that group."}
  private
    before_save {|membership| membership.user_id = (User.find_by(email: membership.email)).id }
    before_save {|membership| membership.group_id = (Group.find_by(title: membership.title)).id }
end

app/models/message.rb
class Message < ActiveRecord::Base
  CATEGORY_TYPES = ["Urgent", "Job", "News", "Event"]
  belongs_to :user
  has_many :comments
  acts_as_votable
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :event_comments, :dependent => :destroy
  acts_as_voter
  enum role: [:User, :Lead, :Business, :Admin]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to home_path, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    user = User.find_by(id: @message.user_id)
    points = user.points + 1
    if (current_user.voted_as_when_voting_on @message) == true
      #Do nothing
    else
      user.update_column(:points, points)
    end
    @message.upvote_from current_user
    redirect_to home_path
  end

  def downvote
    user = User.find_by(id: @message.user_id)
    if user.points > 0
      points = user.points - 1
    else
      points = 0
    end
    if (current_user.voted_as_when_voting_on @message) == false
      #Do nothing
    else
      user.update_column(:points, points)
    end
    @message.downvote_from current_user
    redirect_to home_path
  end

  def count
    @current_user.find_voted_items
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :content, :category, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= bootstrap_form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.select :category, Message::CATEGORY_TYPES,
                  prompt: 'Select a category' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message, class:"btn btn-secondary btn-sm" %> |
<%= link_to 'Back', messages_path, class:"btn btn-secondary btn-sm" %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.content %></td>
        <td><%= message.category %></td>
        <td><%= message.user %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', home_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="lol text-left">
  <p>
    <strong>Title:</strong>
    <%= @message.title %>
  </p>
  
  <p>
    <strong>Content:</strong>
    <%= @message.content %>
  </p>
  
  <p>
    <strong>Category:</strong>
    <%= @message.category %>
  </p>

  <p>
  	Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %>
  ago </p>
</div>

<h3>Comments:</h3>
<%= render @message.comments %>

<h3>Reply to Message:</h3>
<%= render 'comments/form' %>

<% if @message.user_id == current_user.id || current_user.Admin? %>
<%= link_to 'Edit', edit_message_path(@message), class:"btn btn-secondary btn-sm" %> |
<%= link_to 'Back', home_path, class:"btn btn-secondary btn-sm" %> |
<%= link_to 'Destroy', message_path,class:"btn btn-secondary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>