config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :blog_articals
  resources :events do
    resources :event_comments
  end
  resources :emails
  resources :business_messages
  resources :group_messages
  resources :private_messages
  resources :memberships
  resources :groups
  resources :messages do
    resources :comments
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  
  get 'feed' => 'blog_articles#feed'
  get 'webhook' => 'feeds#webhook'
  post 'webhook' => 'feeds#webhook' 
  get 'subscribe' => 'feeds#subscribe'
  get 'home/index'
  get 'home/profile'
  get 'home/calendar'
  get 'home/leadCandidates'
  get 'home/currentLeads'
  get 'home/userDirectory'
  post 'home/promote'
  post 'home/demote'
  
  
  root 'home#index', as: 'home' 

end

app/models/blog_artical.rb
class BlogArtical < ActiveRecord::Base
end

app/models/business_message.rb
class BusinessMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :event_comments
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :entries, dependent: :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
    after_create :establish_membership
    
    def establish_membership
        Membership.create!(title: self.title, email: (User.find_by(id: self.user_id)).email)
        
    end
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
   private
    before_save {|message| message.group_id = (Group.find_by(title: message.group_name)).id }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :email, uniqueness: { scope: [:title], message: "User is already associated with that group."}
  private
    before_save {|membership| membership.user_id = (User.find_by(email: membership.email)).id }
    before_save {|membership| membership.group_id = (Group.find_by(title: membership.title)).id }
end

app/models/message.rb
class Message < ActiveRecord::Base
  CATEGORY_TYPES = ["Urgent", "Job", "News", "Event"]
  belongs_to :user
  has_many :comments
  acts_as_votable
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :event_comments, :dependent => :destroy
  acts_as_voter
  enum role: [:User, :Lead, :Business, :Admin]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  def subscribe
    uri = URI.parse params[:hub]
post_params = {
  'hub.mode' => 'subscribe',
  'hub.topic' => params[:topic],
  'hub.callback' => 'http://finalproject.herokuapp.com/webhook',
}
Net::HTTP.post_form uri, post_params

respond_to do |format|
  format.html { redirect_to :feeds, notice: 'subscription added' }
end
  end

  def webhook
    @challenge = params['hub.challenge']

  # setup doc to be a usable Nokogiri object
  xml = request.body.read
  xml.gsub!(/\n */, '')
  doc = Nokogiri::XML(xml)
  doc.remove_namespaces!

  # ensure doc is a Nokogiri object before continuing
  unless doc.xpath('.//title')[0].nil?

    # find a feed or create a new one
    feed_url = doc.xpath('.//feed/status')[0].attribute('feed').value
    @feed = Feed.find_or_create_by(feed_url: feed_url)
    @feed.title = doc.xpath('.//feed/title')[0].inner_text
    @feed.save!

    doc.xpath('.//feed/entry').each do |entry|
      entry_id = entry.xpath('./id')[0].inner_text
      @entry = Entry.find_or_create_by(feed_id: @feed.id, entry_id: entry_id)
      @entry.title = entry.xpath('./title')[0].inner_text
      @entry.body = entry.xpath('./summary')[0].inner_text
      @entry.author = entry.xpath('./author/name')[0].inner_text
      @entry.save!
    end

  else
    puts 'PROBLEM: rss message empty'
  end

  respond_to do |format|
    format.html { render plain: @challenge, status: 200 }
  end
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title, :feed_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/feeds/_form.html.erb
<%= simple_form_for(@feed) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :feed_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feeds/_subscribe.html.erb
<%= form_tag subscribe_path, method: :get do %>
  <fieldset>
    <legend>
      Subscribe
    </legend>
    <div class="field">
      <%= label_tag :hub, "Hub: " %><br>
      <%= text_field_tag :hub, params[:hub] %>
    </div>
    <div class="field">
      <%= label_tag :topic, "Topic: " %><br>
      <%= text_field_tag :topic, params[:topic] %>
    </div>
    <div class="actions">
      <%= submit_tag "Subscribe" %>
    </div>
  </fieldset>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Feed url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.feed_url %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Feed url:</strong>
  <%= @feed.feed_url %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>