config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :blog_articals
  resources :events do
    resources :event_comments
  end
  resources :emails
  resources :business_messages
  resources :group_messages
  resources :private_messages
  resources :memberships
  resources :groups
  resources :messages do
    resources :comments
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  
  get 'feed' => 'blog_articles#feed'
  get 'webhook' => 'feeds#webhook'
  post 'webhook' => 'feeds#webhook' 
  get 'subscribe' => 'feeds#subscribe'
  get 'home/index'
  get 'home/profile'
  get 'home/calendar'
  get 'home/leadCandidates'
  get 'home/currentLeads'
  get 'home/userDirectory'
  post 'home/promote'
  post 'home/demote'
  
  
  root 'home#index', as: 'home' 

end

app/models/blog_artical.rb
class BlogArtical < ActiveRecord::Base
end

app/models/business_message.rb
class BusinessMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :event_comments
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :entries, dependent: :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
    after_create :establish_membership
    
    def establish_membership
        Membership.create!(title: self.title, email: (User.find_by(id: self.user_id)).email)
        
    end
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
   private
    before_save {|message| message.group_id = (Group.find_by(title: message.group_name)).id }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :email, uniqueness: { scope: [:title], message: "User is already associated with that group."}
  private
    before_save {|membership| membership.user_id = (User.find_by(email: membership.email)).id }
    before_save {|membership| membership.group_id = (Group.find_by(title: membership.title)).id }
end

app/models/message.rb
class Message < ActiveRecord::Base
  CATEGORY_TYPES = ["Urgent", "Job", "News", "Event"]
  belongs_to :user
  has_many :comments
  acts_as_votable
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :event_comments, :dependent => :destroy
  acts_as_voter
  enum role: [:User, :Lead, :Business, :Admin]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @memberships = Membership.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @memberships = Membership.all
    @allGroupMessages = GroupMessage.all
    @currentMessages = Array.new
    
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1><b>Editing: <%= @group.title %> </b></h1>

<%= bootstrap_form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
   <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1><u>Your Groups</u></h1>

 
  
   <table class="table text-center"> 
<thead>
  <tr>
    <td><b>Group Name</b></td> 
    <td><b>Group Description</b></td>
    <th>Show Group</th>
    <th>Edit Group</th>
    <th>Destroy Group</th>
   </tr>
</thead>
  <tbody>
    <% @memberships.each do |member| %>
      <% if member.user_id == current_user.id %>
        <tr>   
           <td><b><%= member.title %></b></td>
           <td><b> <%= (Group.find_by(title: member.title)).description %></b></td>
            <td>
              <%= link_to 'Show', Group.find_by(title: member.title) %>
            </td>
            <td>
              <% if (Group.find_by(title: member.title)).user_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(Group.find_by(title: member.title)) %> 
              <% else %>
                Edit
              <% end %>
            </td>
            <td>
              <% if (Group.find_by(title: member.title)).user_id == current_user.id %>
                <%= link_to 'Destroy', Group.find_by(title: member.title), method: :delete, data: { confirm: 'Are you sure?'} %> 
              <% else %>
                Destroy
              <% end %>
            </td>
        </tr>
      <% end %>
    <% end %> 
  </tbody>
</table>
 
 
<br><br><br>
 
<table class="table"> 
  <tbody>
    <tr>    
      <td>
        <%= button_to('Create New Group', new_group_path, :method => :get,  class:"btn btn-small btn-default") %>
      </td>
      <td>
        <%= button_to('Add Users To Groups', new_membership_path, :method => :get,  class:"btn btn-small btn-default") %> 
      </td>
      <td>
        <%= button_to('Post Group Message', new_group_message_path, :method => :get, class: "btn btn-small btn-default") %> 
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
  
</table>

 

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %> 

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<style>
  .entry2{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    background-color: white;
  }
</style>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @group.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Members:</strong>
  <% @memberships.each do |member| %>
    <% if member.group_id == @group.id %>
      <p><%= member.email %> </p>
    <% end %>
  <% end %>
</p>
<div class="entry text-center">
    <% @allGroupMessages.each do |message| %>
      <% if message.group_id == @group.id %>
      <div class = "entry2 text-center">
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        <% if message.user_id == current_user.id %>
        <p>
          <%= link_to 'Edit', edit_group_message_path(message) %>
          <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
        <% end %>
      </div>
      <% end %>
    <% end %>
</div>

<%= link_to 'Back', groups_path %>