config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :blog_articals
  resources :events do
    resources :event_comments
  end
  resources :emails
  resources :business_messages
  resources :group_messages
  resources :private_messages
  resources :memberships
  resources :groups
  resources :messages do
    resources :comments
    member do
      put "like" => "messages#upvote"
      put "unlike" => "messages#downvote"
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  
  get 'feed' => 'blog_articles#feed'
  get 'webhook' => 'feeds#webhook'
  post 'webhook' => 'feeds#webhook' 
  get 'subscribe' => 'feeds#subscribe'
  get 'home/index'
  get 'home/profile'
  get 'home/calendar'
  get 'home/leadCandidates'
  get 'home/currentLeads'
  get 'home/userDirectory'
  post 'home/promote'
  post 'home/demote'
  
  
  root 'home#index', as: 'home' 

end

app/models/blog_artical.rb
class BlogArtical < ActiveRecord::Base
end

app/models/business_message.rb
class BusinessMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :event_comments
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :entries, dependent: :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
    after_create :establish_membership
    
    def establish_membership
        Membership.create!(title: self.title, email: (User.find_by(id: self.user_id)).email)
        
    end
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
   private
    before_save {|message| message.group_id = (Group.find_by(title: message.group_name)).id }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :email, uniqueness: { scope: [:title], message: "User is already associated with that group."}
  private
    before_save {|membership| membership.user_id = (User.find_by(email: membership.email)).id }
    before_save {|membership| membership.group_id = (Group.find_by(title: membership.title)).id }
end

app/models/message.rb
class Message < ActiveRecord::Base
  CATEGORY_TYPES = ["Urgent", "Job", "News", "Event"]
  belongs_to :user
  has_many :comments
  acts_as_votable
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :event_comments, :dependent => :destroy
  acts_as_voter
  enum role: [:User, :Lead, :Business, :Admin]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!
  layout "profile", only: [:profile, :leadCandidates, :currentLeads, :userDirectory]
  
  def index
    @messages = Message.all
  end
  
  def profile
    @messages = Message.all
    @userMessages = Array.new
    @messages.each do |message|
      if message.user_id == current_user.id
        @userMessages.push(message)
      end
    end
    
    @privateMessages = PrivateMessage.all
    @inbox = Array.new
    @privateMessages.each do |message|
      if message.to == current_user.email
        @inbox.push(message)
      end
    end

    @userBookmarks = @current_user.find_up_voted_items
  end
  
 
  def calendar
    @events = Event.all
  end
 
  def leadCandidates
    @allUsers = User.where(:role => 0)
    @possibleLeads = Array.new
    @allUsers.each do |user|
      if user.points > 50
        @possibleLeads.push(user)
      end
    end
  end
  
  def currentLeads
    @allLeads = User.where(:role => 1)
    @leads = Array.new
    @allLeads.each do |lead|
      if lead.id != current_user.id
        @leads.push(lead)
      end
    end
  end
  
  def userDirectory
    @users = User.all
  end
  
  def promote
    user = User.find(params[:id])
    user.update_column(:role, 1)
    redirect_to home_leadCandidates_path
  end
 
  def demote
    lead = User.find(params[:id])
    lead.update_column(:role, 0)
    redirect_to home_currentLeads_path
  end
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/calendar.html.erb
 <style>
     .th{
         width: 250px;
          
         border-style: solid ;
     }
     #event a {
       color: #FF0000;
     }
 </style>
 <%= month_calendar events: @events do |date, events| %>
  <b><u><%= date.month %>-<%= date.day %></u></b>

  <% events.each do |event| %>
    <div>
      <li id="event"><%= link_to event.name, event %></li>
    </div>
  <% end %>
<% end %>

app/views/home/currentLeads.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Current Leads</h1>

<table class="table text-center"> 
  <thead>
    <tr>
      <td><b>Email</b></td> 
      <td><b>Points</b></td>
      <th>Demote</th>
   </tr>
  </thead>
  <tbody>
    <% @leads.each do |lead| %>
      <tr>   
        <td><b><%= lead.email %></b></td>
        <td><b> <%= lead.points %></b></td>
        <td><%= link_to "Demote", home_demote_path(:id => lead.id), method: :post %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

app/views/home/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>


<h1><u>Message Board</u></h1>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#all"><b>All</b></a></li>
  <li><a data-toggle="tab" href="#urgent"><b>Urgent</b></a></li>
  <li><a data-toggle="tab" href="#news"><b>News</b></a></li>
  <li><a data-toggle="tab" href="#job"><b>Job</b></a></li>
  <li><a data-toggle="tab" href="#event"><b>Event</b></a></li>
</ul>
<div class="tab-content">
  <div id="all" class="tab-pane fade in active">
    <% @messages.reverse.each do |message| %>
      <div class="entry text-left">
        <h3><u><%= link_to message.title,message_path(message) %></u></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        
        <%= link_to "Like", like_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_upvotes.size %></span>

          <%= link_to "UnLike", unlike_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_downvotes.size %></span>
          </button>
          <%# end %>
      </div>
    <% end %>
  </div>
  <div id="urgent" class="tab-pane fade">
    <% @messages.reverse.each do |message| %>
      <% if message.category == "Urgent" %>
      <div class="entry text-left">
        <h3><%= link_to message.title,message_path(message) %></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        <%= link_to "Like", like_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_upvotes.size %></span>

          <%= link_to "UnLike", unlike_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_downvotes.size %></span>
          </button>
       
      </div>
      <% end %>
    <% end %>
  </div>
  <div id="news" class="tab-pane fade">
    <% @messages.reverse.each do |message| %>
      <% if message.category == "News" %>
      <div class="entry text-left">
        <h3><%= link_to message.title,message_path(message) %></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        <%= link_to "Like", like_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_upvotes.size %></span>

          <%= link_to "UnLike", unlike_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_downvotes.size %></span>
          </button>
        
      </div>
      <% end %>
    <% end %>
  </div>
  <div id="job" class="tab-pane fade">
    <% @messages.reverse.each do |message| %>
      <% if message.category == "Job" %>
      <div class="entry text-left">
        <h3><%= link_to message.title,message_path(message) %></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        <%= link_to "Like", like_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_upvotes.size %></span>

          <%= link_to "UnLike", unlike_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_downvotes.size %></span>
          </button>
        
      </div>
      <% end %>
    <% end %>
  </div>
  <div id="event" class="tab-pane fade">
    <% @messages.reverse.each do |message| %>
      <% if message.category == "Event" %>
      <div class="entry text-left">
        <h3><%= link_to message.title,message_path(message) %></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        <%= link_to "Like", like_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_upvotes.size %></span>

          <%= link_to "UnLike", unlike_message_path(message), method: :put  %>
          
              <span class="badge"><%= message.get_downvotes.size %></span>
          </button>
        
      </div>
      <% end %>
    <% end %>
  </div>
</div>
<% if current_user.role != "Business" %>
<p>
  <%= button_to('Post New Message', new_message_path, :method => :get, class: "btn btn-small btn-default") %>
</p>
<% end %>

app/views/home/leadCandidates.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Possible Leads</h1>

<table class="table text-center"> 
  <thead>
    <tr>
      <td><b>Email</b></td> 
      <td><b>Points</b></td>
      <th>Promote</th>
   </tr>
  </thead>
  <tbody>
    <% @possibleLeads.each do |user| %>
      <tr>   
        <td><b><%= user.email %></b></td>
        <td><b> <%= user.points %></b></td>
        <td><%= link_to "Promote", home_promote_path(:id => user.id), method: :post %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

app/views/home/profile.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>


<h1>Your Profile</h1>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#userMessages">Your Public Messages</a></li>
  <li><a data-toggle="tab" href="#inbox">Inbox</a></li>
  <li><a data-toggle="tab" href="#bookmarks">Bookmarks</a></li>
</ul>
<div class="tab-content">
  <div id="userMessages" class="tab-pane fade in active">
    <% @userMessages.reverse.each do |message| %>
      <div class="entry text-left">
        <h3><u><%= link_to message.title,message_path(message) %></u></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
        
      </div>
    <% end %>
  </div>
  <div id="inbox" class="tab-pane fade">
    <% @inbox.reverse.each do |message| %>
      <div class="entry text-left">
        <h3><u>From: <%= (User.find_by(id: message.user_id)).email %></u></h3>
        <p><%= sanitize(message.content) %></p>
      </div>
    <% end %>
  </div>
  <div id="bookmarks" class="tab-pane fade">
    <% @userBookmarks.reverse.each do |message| %>
      <div class="entry text-left">
        <h3><u><%= link_to message.title,message_path(message) %></u></h3>
        <p><%= sanitize(message.content) %></p>
        <p>Posted by: <%= (User.find_by(id: message.user_id)).email %></p>
      </div>
    <% end %>
  </div>
</div>
<p>
  <%= button_to('Send Private Message', new_private_message_path, :method => :get, class: "btn btn-small btn-default") %>
</p>

app/views/home/userDirectory.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>User Directory</h1>

<table class="table text-center"> 
  <thead>
    <tr>
      <td><b>Email</b></td> 
      <th>Delete</th>
   </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if ((user.role != "Admin") && (user.id != current_user.id)) %>
      <tr>   
        <td><b><%= user.email %></b></td>
        <td><%= link_to "Destroy", destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %></td>
      </tr>
      <% end %>
    <% end %> 
  </tbody>
</table>